server:
  port: 8085
spring:
  application:
    name: ai-agent-service
eureka:
  client:
    webclient:
      enabled: true
openai:
  api:
    key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o-mini}
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:StockMarketAgentBot}
    token: ${TELEGRAM_BOT_TOKEN:}
