server:
  port: 8083
spring:
  application:
    name: company-service
  datasource:
    url: jdbc:h2:mem:companydb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
