server:
  port: 8084
spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:h2:mem:stockdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
